### ISSUE TITLE
[0.14.1-1] Myloader segmentation fault

### ISSUE THREAD

**Issue by Vormillion** [mydumper/mydumper#1081]
Hi,

I have a dump from Aurora (sql_mode is set to 0).
mydumper -h ENDPOINT -u USER -p PASSWORD -B SCHEMA --skip-definer -k -G -c -T {tables_list_arg} -o SCHEMA_DIR

I have Centos7 instance (4 cores) from where I'm running myloader:
myloader -h ENDPOINT -u USER -p 'PASSWORD' -B SCHEMA --innodb-optimize-keys  --verbose=3 -d SCHEMA_DIR -o

Without specifying "-t" parameters myloader is using 4 threads according to documentation. I'm getting segmentation fault:

`
[centos@ip-10-15-148-128 nonprod-db-import]$ gdb myloader /tmp/cores/core.myloader.25856
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/myloader...(no debugging symbols found)...done.
[New LWP 25860]
[New LWP 25864]
[New LWP 25867]
[New LWP 25868]
[New LWP 25865]
[New LWP 25858]
[New LWP 25857]
[New LWP 25861]
[New LWP 25859]
[New LWP 25869]
[New LWP 25856]
[New LWP 25862]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `myloader -h REDACTED.'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000428cc7 in worker_index_thread ()
Missing separate debuginfos, use: debuginfo-install mydumper-0.14.1-1.x86_64
`

I tried to lower number of threads to 3
myloader -h ENDPOINT -u USER -p 'PASSWORD' -B SCHEMA --innodb-optimize-keys  --verbose=3 -d SCHEMA_DIR -o -t 3
Again segmentation fault:
`
[centos@ip-10-15-148-128 nonprod-db-import]$ gdb myloader /tmp/cores/core.myloader.26990
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/myloader...(no debugging symbols found)...done.
[New LWP 26995]
[New LWP 26996]
[New LWP 26998]
[New LWP 26992]
[New LWP 26991]
[New LWP 26993]
[New LWP 26999]
[New LWP 27001]
[New LWP 26990]
[New LWP 27000]
[New LWP 26994]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `myloader -h REDACTED.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f285196af65 in g_mutex_lock () from /lib64/libglib-2.0.so.0
Missing separate debuginfos, use: debuginfo-install mydumper-0.14.1-1.x86_64
`

**Comment by Vormillion** [comment]
Hi,

I just tested. Looks like everything works fine with latest prerelease.
