### ISSUE TITLE
[BUG] segfault when dumping

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#1250]
**Describe the bug**
Launching mydumper just segfault

**To Reproduce**
Command executed:
* mydumper with all the parameters
```
[~]: mydumper --defaults-file=/etc/mysql/debian.cnf --triggers --events --routines --compress --logfile="/var/backups/mysql/sauvergarde.2023-08-08-14h41.log" --outputdir="/var/backups/mysql/2023-08-08-14h41" --regex '^(?!(test\.|sys\.))'  --long-query-guard 120 --kill-long-queries --verbose 3 --no-backup-locks
Segmentation fault

```

What mydumper and myloader version has been used?
```
[~]: mydumper -V
mydumper v0.15.1-3, built against MySQL 8.0.33-25 with SSL support
```

**Log**
If applicable, add the --verbose 3 / -v 3 and --logfile / -L <filename> to the execution of the command and upload the file.
```
2023-08-08 16:08:01 [INFO] - MyDumper backup version: 0.15.1-3
2023-08-08 16:08:01 [INFO] - Config file loaded
2023-08-08 16:08:01 [INFO] - Connection via default library settings
2023-08-08 16:08:01 [INFO] - Connected to a Percona server
2023-08-08 16:08:01 [INFO] - Acquiring Global lock
2023-08-08 16:08:01 [INFO] - Sending Flush Table
2023-08-08 16:08:01 [INFO] - Acquiring FTWRL
2023-08-08 16:08:01 [INFO] - Started dump at: 2023-08-08 16:08:01
2023-08-08 16:08:01 [INFO] - conf created
2023-08-08 16:08:01 [INFO] - End job creation
2023-08-08 16:08:01 [INFO] - Creating workers
2023-08-08 16:08:01 [INFO] - Waiting pid started
2023-08-08 16:08:01 [INFO] - Starting Non-InnoDB tables
2023-08-08 16:08:01 [INFO] - Thread 2: connected using MySQL connection ID 83381
2023-08-08 16:08:01 [INFO] - Thread 1: connected using MySQL connection ID 83382
2023-08-08 16:08:01 [INFO] - Thread 3: connected using MySQL connection ID 83383
2023-08-08 16:08:01 [INFO] - Thread 4: connected using MySQL connection ID 83384
2023-08-08 16:08:01 [DEBUG] - Thread 3: Start trasaction #0
2023-08-08 16:08:01 [DEBUG] - Thread 2: Start trasaction #0
2023-08-08 16:08:01 [DEBUG] - Thread 4: Start trasaction #0
2023-08-08 16:08:01 [DEBUG] - Thread 1: Start trasaction #0
```

**Environment (please complete the following information):**
 - OS version: debian 10
 - MyDumper version: mydumper v0.15.1-3, built against MySQL 8.0.33-25 with SSL support

It justsegfault with no idea why. strace show:

```
fstat(7, {st_dev=makedev(0x9, 0x79), st_ino=5259309, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=0, st_size=0, st_atime=1691503681 /* 2023-08-08T16:08:01.528606826+0200 */, st_atime_nsec=528606826, st_mtime=1691504040 /* 2023-08-08T16:14:00.246183162+0200 */, st_mtime_nsec=246183162, st_ctime=1691504040 /* 2023-08-08T16:14:00.246183162+0200 */, st_ctime_nsec=246183162}) = 0
write(3, "2023-08-08 16:14:00 [INFO] - Started dump at: 2023-08-08 16:14:00\n", 66) = 66
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb144e26000
mprotect(0x7fb144e27000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb145625e70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb1456269d0, tls=0x7fb145626700, child_tidptr=0x7fb1456269d0) = 2617
write(3, "2023-08-08 16:14:00 [INFO] - conf created\n", 42) = 42
write(3, "2023-08-08 16:14:00 [INFO] - End job creation\n", 46) = 46
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb144625000
mprotect(0x7fb144626000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb144e24e70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb144e259d0, tls=0x7fb144e25700, child_tidptr=0x7fb144e259d0) = 2618
write(3, "2023-08-08 16:14:00 [INFO] - Creating workers\n", 46) = 46
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb1377ff000
mprotect(0x7fb137800000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb137ffee70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb137fff9d0, tls=0x7fb137fff700, child_tidptr=0x7fb137fff9d0) = 2619
futex(0x7fb1473e8f38, FUTEX_WAKE_PRIVATE, 1) = 1
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb136ffe000
mprotect(0x7fb136fff000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb1377fde70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb1377fe9d0, tls=0x7fb1377fe700, child_tidptr=0x7fb1377fe9d0) = 2620
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb1367fd000
mprotect(0x7fb1367fe000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb136ffce70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb136ffd9d0, tls=0x7fb136ffd700, child_tidptr=0x7fb136ffd9d0) = 2621
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fb135ffc000
mprotect(0x7fb135ffd000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fb1367fbe70, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fb1367fc9d0, tls=0x7fb1367fc700, child_tidptr=0x7fb1367fc9d0) = 2622
futex(0x7fb1473e8f38, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x563e1c99c3e0, FUTEX_WAIT_PRIVATE, 0, NULL) = ?
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by davidducos** [comment]
@aqueos 
Can you try `--defaults-extra-file=/etc/mysql/debian.cnf` instead of `--defaults-file=/etc/mysql/debian.cnf` ?

**Comment by aqueos** [comment]
same result:
```
:[~]: mydumper  --defaults-extra-file=/etc/mysql/debian.cnf --logfile="/var/backups/mysql/sauvergarde.2023-08-08-14h41.log" --outputdir="/var/backups/mysql/2023-08-08-14h41"   --verbose 3 --no-backup-locks
Segmentation fault

```

also tried a specific file with just the [mydumper]
section in default and default-extra but segfault also.

**Comment by aqueos** [comment]
this is a mysql server 5.7 on this one that was upgraded in place from debian 8 to debian 9 to debian 10 and mysql from 5.6 to 5.7 before installing mydumper, old version was failing so i installed latest release with same issue. bzip2 and gzip are installed in /bin

done mysqlupgrade and mysqlcheck with no issue. mysqldump works.

**Comment by davidducos** [comment]
Hi @aqueos thanks for the info. Can you run mydumper with gdb? so we can understand where might be the bug?

**Comment by aqueos** [comment]
yes, i really dont know how to use it so:

```
(gdb) run
Starting program: /usr/bin/mydumper --defaults-extra-file=/etc/mysql/mydumper.cnf --logfile=/var/backups/mysql/sauvergarde.2023-08-08-14h41.log --outputdir=/var/backups/mysql/2023-08-08-14h41 --verbose 3 --no-backup-locks
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6cb5700 (LWP 6643)]
[New Thread 0x7ffff64b4700 (LWP 6644)]
[New Thread 0x7ffff5cb3700 (LWP 6645)]
[New Thread 0x7ffff54b2700 (LWP 6646)]
[New Thread 0x7ffff4cb1700 (LWP 6647)]
[New Thread 0x7fffdffff700 (LWP 6648)]
[New Thread 0x7fffdf7fe700 (LWP 6649)]
[New Thread 0x7fffdeffd700 (LWP 6650)]

Thread 6 "mydumper" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4cb1700 (LWP 6647)]
0x00005555555d2b20 in mysql_fetch_row ()

```

**Comment by davidducos** [comment]
Hi @aqueos 
Can you execute command `backtrace`?
```
(gdb) bt
```

**Comment by aqueos** [comment]
here it is:

```
(gdb) run
Starting program: /usr/bin/mydumper --defaults-extra-file=/etc/mysql/mydumper.cnf --logfile=/var/backups/mysql/sauvergarde.2023-08-08-14h41.log --outputdir=/var/backups/mysql/2023-08-08-14h41 --verbose 3 --no-backup-locks
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6cb5700 (LWP 20789)]
[New Thread 0x7ffff64b4700 (LWP 20790)]
[New Thread 0x7ffff5cb3700 (LWP 20791)]
[New Thread 0x7ffff54b2700 (LWP 20792)]
[New Thread 0x7ffff4cb1700 (LWP 20793)]
[New Thread 0x7fffdffff700 (LWP 20794)]
[New Thread 0x7fffdf7fe700 (LWP 20795)]
[New Thread 0x7fffdeffd700 (LWP 20796)]

Thread 9 "mydumper" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdeffd700 (LWP 20796)]
0x00005555555d2b20 in mysql_fetch_row ()
(gdb) bt
#0  0x00005555555d2b20 in mysql_fetch_row ()
#1  0x00005555555b8829 in initialize_consistent_snapshot (td=0x555555d43a18) at /tmp/src/mydumper/src/mydumper_working_thread.c:525
#2  0x00005555555bbe24 in working_thread (td=0x555555d43a18) at /tmp/src/mydumper/src/mydumper_working_thread.c:1169
#3  0x00007ffff79ce4d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7fabfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007ffff744606f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
