### ISSUE TITLE
Build of 0.15.1-3 fails on: Building HTML documentation with Sphinx

### ISSUE THREAD

**Issue by 3eka** [mydumper/mydumper#1325]
Hi,

trying to build mydumper on OpenIndiana, GCC 12, and python-3.9:
```
...
[ 97%] Building HTML documentation with Sphinx
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/lib/python3.9/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/lib/python3.9/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/usr/lib/python3.9/vendor-packages/jinja2/__init__.py)
gmake[2]: *** [docs/CMakeFiles/doc_html.dir/build.make:71: docs/CMakeFiles/doc_html] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:238: docs/CMakeFiles/doc_html.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Looking at the error, seems that _environmentfilter_ is missing in `jinja2`... Here versions:
```
:; pkg list jinja2 sphinx
NAME (PUBLISHER)                                  VERSION                    IFO
library/python/jinja2                             3.1.2-2023.0.0.0           i--
library/python/sphinx                             7.2.6-2023.0.0.0           i--
```
So: how I can pass building WITH HTML docs, using Sphinx (I know I can use `-DBUILD_DOCS=OFF` to avoid it...)?

Thanks for this excellent tool.
Regards.

**Comment by davidducos** [comment]
Hi @3eka 
I was trying to understand the issue and I found https://github.com/readthedocs/readthedocs.org/issues/9038 and then I jumped to https://github.com/readthedocs/readthedocs.org/issues/9037#issuecomment-1077818554.
I might need to install sphinx to build the documentation and find this kind of issues.

**Comment by davidducos** [comment]
Hi @3eka 
You will be able to find the documentation on https://mydumper.github.io/mydumper from now on. 
And we also create this repo https://github.com/mydumper/mydumper_docs, where any changes are automatically deployed on the website.
