### ISSUE TITLE
[BUG] mydumper segfault : segfault at 70, got coredump

### ISSUE THREAD

**Issue by aqueos** [mydumper/mydumper#1385]
**Describe the bug**

i got random segfault on mydumper 0.15.6

```
Jan 7 23:06:33 server143 kernel: [652143.865214] mydumper[1597287]: segfault at 70 ip 000055de66137462 sp 00007f5e0fffeb10 error 4 in mydumper[55de6611e000+126000] likely on CPU 6 (core 2, socket 0) 
Jan 8 23:15:53 server143 kernel: [739104.960049] mydumper[2307912]: segfault at 70 ip 000055ad10f06462 sp 00007fa902ffcb10 error 4 in mydumper[55ad10eed000+126000] likely on CPU 6 (core 2, socket 0) 
Jan 9 23:09:07 server143 kernel: [825100.606442] mydumper[3021821]: segfault at 70 ip 000055930a19f462 sp 00007fa8ea7fbb10 error 4 in mydumper[55930a186000+126000] likely on CPU 3 (core 3, socket 0) 
Jan 2 16:56:30 server143 kernel: [197935.567247] mydumper[1719657]: segfault at 70 ip 000055f3a66cc462 sp 00007f63e17f9b10 error 4 in mydumper[55f3a66b3000+126000] likely on CPU 3 (core 3, socket 0) 
Jan 2 17:31:40 server143 kernel: [200045.532317] mydumper[1735564]: segfault at 70 ip 0000555cb65c0462 sp 00007fd13d1f9b10 error 4 in mydumper[555cb65a7000+126000] likely on CPU 6 (core 2, socket 0) 
Jan 3 23:09:02 server143 kernel: [306689.310488] mydumper[2980101]: segfault at 70 ip 0000562e1a418462 sp 00007f3b52fa6b10 error 4 in mydumper[562e1a3ff000+126000] likely on CPU 3 (core 3, socket 0) 
Jan 4 23:06:21 server143 kernel: [392929.050796] mydumper[3685181]: segfault at 70 ip 000055628ba20462 sp 00007f19cd7f9b10 error 4 in mydumper[55628ba07000+126000] likely on CPU 7 (core 3, socket 0) 
Jan 5 23:05:47 server143 kernel: [479295.576699] mydumper[186313]: segfault at 70 ip 000055d2dafa9462 sp 00007f0608ff8b10 error 4 in mydumper[55d2daf90000+126000] likely on CPU 7 (core 3, socket 0) 
Jan 6 23:25:31 server143 kernel: [566881.168677] mydumper[905844]: segfault at 70 ip 000055ce29d4e462 sp 00007f453bffeb10 error 4 in mydumper[55ce29d35000+126000] likely on CPU 2 (core 2, socket 0) 
Jan 4 23:48:53 server230 kernel: [19315354.912236] mydumper[32132]: segfault at 70 ip 000055b9eac50462 sp 00007ff25db72b10 error 4 in mydumper[55b9eac37000+126000] 
Jan 7 23:20:20 server232 kernel: [19572180.705167] mydumper[8256]: segfault at 70 ip 0000556152224462 sp 00007f8a777fdb10 error 4 in mydumper[55615220b000+126000] 
Jan 3 23:34:19 server232 kernel: [19228230.796173] mydumper[28386]: segfault at 70 ip 000055e9fd06b462 sp 00007fd9e9ffab10 error 4 in mydumper[55e9fd052000+126000] 
Nov 29 23:01:44 server232 kernel: [16209396.213928] mydumper[40813]: segfault at 70 ip 00005579cedc0747 sp 00007f9c237fdba0 error 4 in mydumper[5579cedab000+77000]
Jan 8 00:50:43 server233 kernel: [19577833.565924] mydumper[99329]: segfault at 70 ip 000055cb5da4e462 sp 00007fd766ffcb10 error 4 in mydumper[55cb5da35000+126000] 
Nov 13 23:57:38 server324 kernel: [17817034.320808] mydumper[68030]: segfault at 70 ip 000055d8d02b9747 sp 00007f3e88b1cb40 error 4 in mydumper[55d8d02a4000+77000]
Nov 7 23:13:05 server325 kernel: [14313902.737858] mydumper[42946]: segfault at 2a ip 000056230708c720 sp 00007fb9d9907ba0 error 4 in mydumper[562307077000+77000]
Jan 9 23:07:54 server327 kernel: [19792472.273475] mydumper[18909]: segfault at 70 ip 0000559804c3f462 sp 00007f7e7bffeb10 error 4 in mydumper[559804c26000+126000] 
Jan 8 23:40:23 server328 kernel: [11237545.440875] mydumper[1564886]: segfault at 70 ip 000055ba26f090b4 sp 00007f8b2f7fdb50 error 4 in mydumper[55ba26ef0000+124000] likely on CPU 9 (core 9, socket 0) 
```
i also have quite a lot of 

```
Dec 21 23:00:18  kernel: [14602954.871604] traps: mydumper[315745] trap int3 ip:7f5bf3f9fd35 sp:7fff992b6750 error:0 in libglib-2.0.so.0.5800.3[7f5bf3f67000+7f000] 

Dec 21 23:00:26  kernel: [14602962.625418] traps: mydumper[316155] trap int3 ip:7f1254d24ca7 sp:7fff564fb4d0 error:0 in libglib-2.0.so.0.6600.8[7f1254ce8000+88000] 

Dec 21 23:00:53  kernel: [14602989.960647] traps: mydumper[316651] trap int3 ip:7f4da412aca7 sp:7ffee18109e0 error:0 in libglib-2.0.so.0.6600.8[7f4da40ee000+88000] 

Dec 21 23:01:25  kernel: [14603021.978970] traps: mydumper[317246] trap int3 ip:7f9acf46cca7 sp:7ffffa2ee8d0 error:0 in libglib-2.0.so.0.6600.8[7f9acf430000+88000] 

Dec 21 23:04:11  kernel: [14603188.327737] traps: mydumper[319987] trap int3 ip:7f68baf74ca7 sp:7ffda45f1d50 error:0 in libglib-2.0.so.0.6600.8[7f68baf38000+88000] 

Dec 21 23:10:00  kernel: [14603536.788050] traps: mydumper[326153] trap int3 ip:7f2a838acd35 sp:7ffe3d8a6da0 error:0 in libglib-2.0.so.0.5800.3[7f2a83874000+7f000] 

Dec 21 23:11:24  kernel: [14603620.708985] traps: mydumper[328472] trap int3 ip:7f0463469ca7 sp:7ffcf0778ac0 error:0 in libglib-2.0.so.0.6600.8[7f046342d000+88000] 

Dec 21 23:19:13  kernel: [14604089.504948] traps: mydumper[336577] trap int3 ip:7f5d53687d35 sp:7ffe1af8b3d0 error:0 in libglib-2.0.so.0.5800.3[7f5d5364f000+7f000]
```

**To Reproduce**

just the same
	mydumper --defaults-file=/etc/mysql/debian.cnf \
	--triggers --events --routines \
	--logfile="/var/backups/mysql/sauvergarde.${REPERTOIRE}.log" \
	--outputdir="/var/backups/mysql/${REPERTOIRE}" \
	--regex '^(?!(test\.|sys\.))' \
	--rows=10000:100000:0 \
	--long-query-guard 120 --kill-long-queries \
	--verbose 3 --compress=ZSTD

What mydumper and myloader version has been used?
mydumper v0.15.2-6, built against MySQL 8.0.34-26 with SSL support

**Environment (please complete the following information):**
 - OS version: debian 10
 - MyDumper version: [ mydumper --version ] mydumper v0.15.2-6, built against MySQL 8.0.34-26 with SSL support

**Comment by aqueos** [comment]
the error does not trigger at every run, i have this issue randomly. nothing in the log it just logs working on table xxx then nothing.

**Comment by aqueos** [comment]
got a coredump !

```
Reading symbols from /usr/bin/mydumper...done.
[New LWP 2856411]
[New LWP 2855633]
[New LWP 2856413]
[New LWP 2855631]
[New LWP 2855632]
[New LWP 2855634]
[New LWP 2856409]
[New LWP 2856412]
[New LWP 2856410]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mydumper --user=root --triggers --events --routines --logfile=/var/backups/mysq'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  get_estimated_remaining_of (list=0x7fe770c90cc0, mutex=0x5633fe1d5e90) at /tmp/src/mydumper/src/mydumper_write.c:343
343	/tmp/src/mydumper/src/mydumper_write.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe78b7fe700 (LWP 2856411))]
(gdb) bt
#0  get_estimated_remaining_of (list=0x7fe770c90cc0, mutex=0x5633fe1d5e90) at /tmp/src/mydumper/src/mydumper_write.c:343
#1  0x00005633fc04f4cd in get_estimated_remaining_of_all_chunks () at /tmp/src/mydumper/src/mydumper_write.c:351
#2  0x00005633fc04f4f6 in message_dumping_data (tj=0x7fe778001f90) at /tmp/src/mydumper/src/mydumper_write.c:357
#3  0x00005633fc050231 in write_row_into_file_in_sql_mode (conn=0x7fe770001c00, result=0x7fe7704c4d00, tj=0x7fe778001f90) at /tmp/src/mydumper/src/mydumper_write.c:542
#4  0x00005633fc050c33 in write_table_job_into_file (tj=0x7fe778001f90) at /tmp/src/mydumper/src/mydumper_write.c:681
#5  0x00005633fc04d059 in process_none_chunk (tj=0x7fe778001f90, csi=0x7fe77531c6c0) at /tmp/src/mydumper/src/mydumper_chunks.c:60
#6  0x00005633fc048260 in thd_JOB_DUMP (td=0x5633fe26b268, job=0x7fe778002880) at /tmp/src/mydumper/src/mydumper_working_thread.c:453
#7  0x00005633fc04901b in process_job (td=0x5633fe26b268, job=0x7fe778002880) at /tmp/src/mydumper/src/mydumper_working_thread.c:714
#8  0x00005633fc0492b1 in process_queue (queue=0x5633fe218170, td=0x5633fe26b268, p=0x5633fc048f9b <process_job>, f=0x5633fc04e137 <give_me_another_innodb_chunk_step>) at /tmp/src/mydumper/src/mydumper_working_thread.c:784
#9  0x00005633fc0497ed in working_thread (td=0x5633fe26b268) at /tmp/src/mydumper/src/mydumper_working_thread.c:888
#10 0x00007fe793b874d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fe793cf6fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007fe79319006f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by davidducos** [comment]
Hi @aqueos, I thin that this has been fixed on the latest prerelease.

**Comment by aqueos** [comment]
the server where i had 100% segfault is working now with 0.15.7
i will gradualy reactivate mydumper on the servers and see if those are gone.

**Comment by aqueos** [comment]
i dont have anymore segfault but i have some process that goes nuts at 100% cpu for hours.
I will open a new ticket for it.
