### ISSUE TITLE
Error with Glib -segmentation fault

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [mydumper/mydumper#1522]
While restoring im getting this error.

```
GLib:ERROR:../../../glib/gasyncqueue.c:431:g_async_queue_pop_intern_unlocked: assertion failed: (retval || !wait || end_time > 0)
Bail out! GLib:ERROR:../../../glib/gasyncqueue.c:431:g_async_queue_pop_intern_unlocked: assertion failed: (retval || !wait || end_time > 0)
Segmentation fault
```

**Comment by davidducos** [comment]
Hi @BhuviTheDataGuy, 
I need more information to troubleshoot that bug:
- MyDumper OS and MySQL version
- myloader and mydumper logs
- reproducible test case if possible
- core dump
You can use [this template](https://github.com/mydumper/mydumper/issues/new?labels=bug&template=bug_report.md&title=%5BBUG%5D) which contains the list of the useful info that I usually request for bugs.

**Comment by BhuviTheDataGuy** [comment]
Myloader version:
myloader v0.16.3-2, built against MySQL 8.0.36-28 with SSL support

OS:
Ubuntu 20.04.6 LTS

reproducible test case  - No( it was 2TB database, and I have verified that --no-data ran fine, something wrong in the datafiles only) 

Core dump: bt output
```
Core was generated by `myloader --host=xxxxxxxx.ap-south-1.rds.amazonaws'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558ebb38e688 in give_me_next_data_job_conf (conf=0x7ffc66d9b290, rj=0x7f98677fde80) at /tmp/src/mydumper/src/myloader_control_job.c:264
264	/tmp/src/mydumper/src/myloader_control_job.c: No such file or directory.
[Current thread is 1 (Thread 0x7f98677fe700 (LWP 416575))]
(gdb) bt
#0  0x0000558ebb38e688 in give_me_next_data_job_conf (conf=0x7ffc66d9b290, rj=0x7f98677fde80) at /tmp/src/mydumper/src/myloader_control_job.c:264
#1  0x0000558ebb38eb25 in control_job_thread (conf=0x7ffc66d9b290) at /tmp/src/mydumper/src/myloader_control_job.c:389
#2  0x00007f9a5b410ae1 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f9a5b837609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f9a5b04b353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by davidducos** [comment]
Hi @BhuviTheDataGuy,
Thanks for your feedback, it was really useful but I need to request you some more info.
I need you run on gdb this commands:
``` p dbt
p dbt->database
p dbt->database->real_database
p dbt->real_table
p dbt->current_threads
p job
p job->type
```

**Comment by BhuviTheDataGuy** [comment]
```
(gdb) p dbt->database
$1 = (struct database *) 0x558ebc3405c0
(gdb) p dbt->database->real_database
$2 = 0x558ebc340620 "rackdb"
(gdb) p dbt->real_table
$3 = 0x7f98581e4f40 "storeproducts"
(gdb) p dbt->current_threads
$4 = 9
(gdb) p job
$5 = (struct restore_job *) 0x5
(gdb) p job->filename
Cannot access memory at address 0x15
(gdb) p job->type
Cannot access memory at address 0x5
(gdb)
```

**Comment by davidducos** [comment]
Hi @BhuviTheDataGuy, 
Can you share myloader logs?

**Comment by davidducos** [comment]
Hi @BhuviTheDataGuy,
BTW, did you test with latest released version?

**Comment by davidducos** [comment]
Closing until we get feedback.
